/* The following code was generated by JFlex 1.4.3 on 02/06/22 12:29 */

package clases;
import static clases.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 02/06/22 12:29 from the specification file
 * <tt>C:/Users/Usuario/Documents/NetBeansProjects/AnalizadorDeCodigoC_V1/src/clases/Lexer.flex</tt>
 */
public class claseLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\3\1\41\1\6\2\0"+
    "\1\36\1\37\1\7\1\42\1\43\1\35\1\33\1\54\1\34\1\53"+
    "\1\4\12\2\1\55\1\56\1\51\1\52\1\50\2\0\32\1\1\44"+
    "\1\0\1\45\1\0\1\1\1\0\1\25\1\14\1\30\1\13\1\27"+
    "\1\24\1\23\1\17\1\12\1\1\1\32\1\22\1\61\1\21\1\11"+
    "\1\57\1\60\1\20\1\16\1\15\1\26\1\10\1\31\3\1\1\46"+
    "\1\40\1\47\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\14\2\1\11\1\12\1\13\1\14\3\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\2\24\1\25\1\26"+
    "\1\27\1\30\1\31\2\2\1\4\1\32\2\2\1\33"+
    "\1\34\21\2\1\35\1\15\1\24\1\0\4\2\1\36"+
    "\12\2\1\37\7\2\1\0\1\40\5\2\1\41\2\2"+
    "\1\42\1\2\1\43\1\2\1\44\1\45\1\2\1\3"+
    "\1\2\1\46\2\2\1\47\1\50\1\2\1\51\1\2"+
    "\1\52\2\2\1\53\1\2\1\54\1\55\1\2\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\62\0\62"+
    "\0\62\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8"+
    "\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\62\0\62\0\62"+
    "\0\62\0\62\0\u04e2\0\u0514\0\u047e\0\62\0\62\0\62"+
    "\0\62\0\u0546\0\u0578\0\u05aa\0\62\0\u05dc\0\u060e\0\144"+
    "\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e"+
    "\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e"+
    "\0\u0960\0\u0992\0\62\0\62\0\62\0\u09c4\0\u09f6\0\u0a28"+
    "\0\u0a5a\0\u0a8c\0\144\0\u0abe\0\u0af0\0\u0b22\0\u0b54\0\u0b86"+
    "\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80\0\144\0\u0cb2\0\u0ce4"+
    "\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde\0\u0e10\0\144\0\u0e42"+
    "\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a\0\144\0\u0f3c\0\u0f6e\0\144"+
    "\0\u0fa0\0\144\0\u0fd2\0\144\0\144\0\u1004\0\62\0\u1036"+
    "\0\144\0\u1068\0\u109a\0\144\0\144\0\u10cc\0\144\0\u10fe"+
    "\0\144\0\u1130\0\u1162\0\144\0\u1194\0\144\0\144\0\u11c6"+
    "\0\144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\3\1\13\1\14\1\15\1\16\1\17\3\3"+
    "\1\20\1\21\1\22\2\3\1\23\1\24\1\25\1\3"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\3\1\53\63\0"+
    "\2\3\5\0\23\3\24\0\3\3\2\0\1\4\62\0"+
    "\1\5\62\0\1\54\45\0\1\55\10\0\2\3\5\0"+
    "\1\3\1\56\21\3\24\0\3\3\1\0\2\3\5\0"+
    "\11\3\1\57\2\3\1\60\6\3\24\0\3\3\1\0"+
    "\2\3\5\0\1\3\1\61\15\3\1\62\3\3\24\0"+
    "\3\3\1\0\2\3\5\0\2\3\1\57\5\3\1\63"+
    "\12\3\24\0\3\3\1\0\2\3\5\0\10\3\1\64"+
    "\12\3\24\0\3\3\1\0\2\3\5\0\7\3\1\65"+
    "\10\3\1\66\1\67\1\3\24\0\1\3\1\70\1\3"+
    "\1\0\2\3\5\0\1\3\1\71\21\3\24\0\3\3"+
    "\1\0\2\3\5\0\17\3\1\72\3\3\24\0\3\3"+
    "\1\0\2\3\5\0\1\3\1\73\10\3\1\74\2\3"+
    "\1\75\5\3\24\0\3\3\1\0\2\3\5\0\12\3"+
    "\1\76\10\3\24\0\3\3\1\0\2\3\5\0\1\3"+
    "\1\77\5\3\1\100\5\3\1\101\5\3\24\0\3\3"+
    "\1\0\2\3\5\0\7\3\1\102\13\3\24\0\3\3"+
    "\33\0\1\103\16\0\1\55\43\0\1\103\15\0\1\55"+
    "\61\0\1\55\46\0\1\104\62\0\1\104\73\0\1\105"+
    "\43\0\1\106\75\0\1\105\1\0\1\105\60\0\2\105"+
    "\10\0\2\3\5\0\1\3\1\107\6\3\1\110\12\3"+
    "\24\0\3\3\1\0\2\3\5\0\15\3\1\111\5\3"+
    "\24\0\3\3\5\54\1\0\54\54\1\0\2\3\5\0"+
    "\2\3\1\112\20\3\24\0\3\3\1\0\2\3\5\0"+
    "\5\3\1\113\15\3\24\0\3\3\1\0\2\3\5\0"+
    "\16\3\1\114\4\3\24\0\3\3\1\0\2\3\5\0"+
    "\14\3\1\115\6\3\24\0\3\3\1\0\2\3\5\0"+
    "\17\3\1\116\3\3\24\0\3\3\1\0\2\3\5\0"+
    "\16\3\1\117\4\3\24\0\3\3\1\0\2\3\5\0"+
    "\1\3\1\120\21\3\24\0\3\3\1\0\2\3\5\0"+
    "\15\3\1\121\5\3\24\0\3\3\1\0\2\3\5\0"+
    "\2\3\1\122\20\3\24\0\3\3\1\0\2\3\5\0"+
    "\10\3\1\123\12\3\24\0\3\3\1\0\2\3\5\0"+
    "\11\3\1\124\11\3\24\0\3\3\1\0\2\3\5\0"+
    "\5\3\1\125\15\3\24\0\3\3\1\0\2\3\5\0"+
    "\10\3\1\126\12\3\24\0\3\3\1\0\2\3\5\0"+
    "\1\3\1\127\21\3\24\0\3\3\1\0\2\3\5\0"+
    "\12\3\1\130\10\3\24\0\3\3\1\0\2\3\5\0"+
    "\6\3\1\131\14\3\24\0\3\3\1\0\2\3\5\0"+
    "\11\3\1\132\11\3\24\0\3\3\1\0\2\3\5\0"+
    "\15\3\1\133\5\3\24\0\3\3\1\0\2\3\5\0"+
    "\6\3\1\134\14\3\24\0\3\3\1\0\2\3\5\0"+
    "\2\3\1\135\20\3\24\0\3\3\2\0\1\136\60\0"+
    "\2\3\5\0\21\3\1\137\1\3\24\0\3\3\1\0"+
    "\2\3\5\0\2\3\1\140\20\3\24\0\3\3\1\0"+
    "\2\3\5\0\2\3\1\141\20\3\24\0\3\3\1\0"+
    "\2\3\5\0\3\3\1\113\17\3\24\0\3\3\1\0"+
    "\2\3\5\0\4\3\1\142\16\3\24\0\3\3\1\0"+
    "\2\3\5\0\15\3\1\143\5\3\24\0\3\3\1\0"+
    "\2\3\5\0\15\3\1\144\5\3\24\0\3\3\1\0"+
    "\2\3\5\0\17\3\1\145\3\3\24\0\3\3\1\0"+
    "\2\3\5\0\10\3\1\57\12\3\24\0\3\3\1\0"+
    "\2\3\5\0\11\3\1\146\11\3\24\0\3\3\1\0"+
    "\2\3\5\0\5\3\1\147\15\3\24\0\3\3\1\0"+
    "\2\3\5\0\5\3\1\150\15\3\24\0\3\3\1\0"+
    "\2\3\5\0\13\3\1\113\7\3\24\0\3\3\1\0"+
    "\2\3\5\0\20\3\1\151\2\3\24\0\3\3\1\0"+
    "\2\3\5\0\15\3\1\57\5\3\24\0\3\3\1\0"+
    "\2\3\5\0\6\3\1\117\14\3\24\0\3\3\1\0"+
    "\2\3\5\0\17\3\1\152\3\3\24\0\3\3\1\0"+
    "\2\3\5\0\5\3\1\153\15\3\24\0\3\3\1\0"+
    "\2\3\5\0\10\3\1\154\12\3\24\0\3\3\1\0"+
    "\2\3\5\0\17\3\1\155\3\3\24\0\3\3\1\0"+
    "\2\3\5\0\12\3\1\156\10\3\24\0\3\3\2\0"+
    "\1\136\40\0\1\157\17\0\2\3\5\0\11\3\1\160"+
    "\11\3\24\0\3\3\1\0\2\3\5\0\11\3\1\161"+
    "\11\3\24\0\3\3\1\0\2\3\5\0\12\3\1\162"+
    "\10\3\24\0\3\3\1\0\2\3\5\0\16\3\1\163"+
    "\4\3\24\0\3\3\1\0\2\3\5\0\22\3\1\164"+
    "\24\0\3\3\1\0\2\3\5\0\14\3\1\165\6\3"+
    "\24\0\3\3\1\0\2\3\5\0\20\3\1\166\2\3"+
    "\24\0\3\3\1\0\2\3\5\0\7\3\1\167\13\3"+
    "\24\0\3\3\1\0\2\3\5\0\2\3\1\170\20\3"+
    "\24\0\3\3\1\0\2\3\5\0\17\3\1\171\3\3"+
    "\24\0\3\3\1\0\2\3\5\0\5\3\1\172\15\3"+
    "\24\0\3\3\1\0\2\3\5\0\17\3\1\113\3\3"+
    "\24\0\3\3\1\0\2\3\5\0\12\3\1\173\10\3"+
    "\24\0\3\3\1\0\2\3\5\0\7\3\1\174\13\3"+
    "\24\0\3\3\1\0\2\3\5\0\11\3\1\175\11\3"+
    "\24\0\3\3\1\0\2\3\5\0\14\3\1\176\6\3"+
    "\24\0\3\3\1\0\2\3\5\0\5\3\1\177\15\3"+
    "\24\0\3\3\1\0\2\3\5\0\16\3\1\200\4\3"+
    "\24\0\3\3\1\0\2\3\5\0\17\3\1\201\3\3"+
    "\24\0\3\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4600];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\3\11\24\1\5\11\3\1\4\11"+
    "\3\1\1\11\25\1\3\11\1\0\27\1\1\0\20\1"+
    "\1\11\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public claseLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public claseLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 28: 
          { lexeme=yytext(); return DO;
          }
        case 47: break;
        case 30: 
          { lexeme=yytext(); return TIPO_DE_DATO;
          }
        case 48: break;
        case 15: 
          { lexeme=yytext(); return PARENTESIS_CERRAR;
          }
        case 49: break;
        case 44: 
          { lexeme=yytext(); return METODO_PRINTF;
          }
        case 50: break;
        case 35: 
          { lexeme=yytext(); return ELSE;
          }
        case 51: break;
        case 7: 
          { lexeme=yytext(); return COMILLAS;
          }
        case 52: break;
        case 37: 
          { lexeme=yytext(); return CASE;
          }
        case 53: break;
        case 29: 
          { lexeme = yytext(); return OP_INCRE_DECRE;
          }
        case 54: break;
        case 11: 
          { lexeme=yytext(); return MULTIPLICACION;
          }
        case 55: break;
        case 34: 
          { lexeme=yytext(); return METODO_RAIZ;
          }
        case 56: break;
        case 12: 
          { lexeme=yytext(); return MODULO;
          }
        case 57: break;
        case 20: 
          { lexeme = yytext(); return OP_RELACIONAL;
          }
        case 58: break;
        case 26: 
          { lexeme = yytext(); return OP_ATRIBUCION;
          }
        case 59: break;
        case 27: 
          { lexeme=yytext(); return IF;
          }
        case 60: break;
        case 31: 
          { lexeme=yytext(); return FOR;
          }
        case 61: break;
        case 18: 
          { lexeme=yytext(); return LLAVE_ABRIR;
          }
        case 62: break;
        case 22: 
          { lexeme=yytext(); return PUNTO;
          }
        case 63: break;
        case 10: 
          { lexeme=yytext(); return MENOS;
          }
        case 64: break;
        case 9: 
          { lexeme=yytext(); return MAS;
          }
        case 65: break;
        case 16: 
          { lexeme=yytext(); return CORCHETE_ABRIR;
          }
        case 66: break;
        case 14: 
          { lexeme=yytext(); return PARENTESIS_ABRIR;
          }
        case 67: break;
        case 24: 
          { lexeme=yytext(); return DOS_PUNTOS;
          }
        case 68: break;
        case 8: 
          { lexeme=yytext(); return COMILLA_SIMPLE;
          }
        case 69: break;
        case 38: 
          { lexeme=yytext(); return MAIN;
          }
        case 70: break;
        case 25: 
          { lexeme=yytext(); return PUNTO_Y_COMA;
          }
        case 71: break;
        case 3: 
          { lexeme=yytext(); return NUMERO;
          }
        case 72: break;
        case 17: 
          { lexeme=yytext(); return CORCHETE_CERRAR;
          }
        case 73: break;
        case 42: 
          { lexeme=yytext(); return WHILE;
          }
        case 74: break;
        case 46: 
          { lexeme=yytext(); return CONTINUE;
          }
        case 75: break;
        case 21: 
          { lexeme=yytext(); return ASIGNACION;
          }
        case 76: break;
        case 2: 
          { lexeme=yytext(); return IDENTIFICADOR;
          }
        case 77: break;
        case 45: 
          { lexeme=yytext(); return DEFAULT;
          }
        case 78: break;
        case 1: 
          { lexeme=yytext(); return ERROR;
          }
        case 79: break;
        case 39: 
          { lexeme=yytext(); return BREAK;
          }
        case 80: break;
        case 41: 
          { lexeme=yytext(); return METODO_ESPERA;
          }
        case 81: break;
        case 36: 
          { lexeme=yytext(); return CHAR;
          }
        case 82: break;
        case 32: 
          { lexeme=yytext(); return METODO_POW;
          }
        case 83: break;
        case 13: 
          { lexeme=yytext(); return OP_LOGICO;
          }
        case 84: break;
        case 40: 
          { lexeme=yytext(); return METODO_SCANF;
          }
        case 85: break;
        case 23: 
          { lexeme=yytext(); return COMA;
          }
        case 86: break;
        case 4: 
          { /*Ignore*/
          }
        case 87: break;
        case 43: 
          { lexeme=yytext(); return SWITCH;
          }
        case 88: break;
        case 33: 
          { lexeme = yytext(); return OP_BOOLEANO;
          }
        case 89: break;
        case 19: 
          { lexeme=yytext(); return LLAVE_CERRAR;
          }
        case 90: break;
        case 6: 
          { return SALTO_DE_LINEA;
          }
        case 91: break;
        case 5: 
          { lexeme=yytext(); return DIVISION;
          }
        case 92: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
