
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 04 07:48:33 CDT 2022
//----------------------------------------------------

package clases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 43;
  public static final int SALTO_DE_LINEA = 2;
  public static final int OP_ATRIBUCION = 32;
  public static final int CHAR = 6;
  public static final int PUNTO_Y_COMA = 38;
  public static final int CASE = 13;
  public static final int CORCHETE_CERRAR = 28;
  public static final int METODO_RESERVADO = 40;
  public static final int DOS_PUNTOS = 37;
  public static final int CONTINUE = 15;
  public static final int FOR = 11;
  public static final int PARENTESIS_ABRIR = 25;
  public static final int IDENTIFICADOR = 44;
  public static final int OP_BOOLEANO = 34;
  public static final int MAIN = 42;
  public static final int IF = 7;
  public static final int OP_RELACIONAL = 31;
  public static final int EOF = 0;
  public static final int COMILLAS = 3;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int CADENA = 45;
  public static final int MODULO = 23;
  public static final int MENOS = 20;
  public static final int NULL = 41;
  public static final int TRY = 17;
  public static final int OP_INCRE_DECRE = 33;
  public static final int BREAK = 14;
  public static final int ERROR = 46;
  public static final int ASIGNACION = 39;
  public static final int SWITCH = 12;
  public static final int LLAVE_CERRAR = 30;
  public static final int ELSE = 8;
  public static final int PUNTO = 35;
  public static final int LLAVE_ABRIR = 29;
  public static final int OP_LOGICO = 24;
  public static final int WHILE = 10;
  public static final int TIPO_DE_DATO = 5;
  public static final int COMILLA_SIMPLE = 4;
  public static final int DEFAULT = 16;
  public static final int CORCHETE_ABRIR = 27;
  public static final int PARENTESIS_CERRAR = 26;
  public static final int DIVISION = 22;
  public static final int DO = 9;
  public static final int MULTIPLICACION = 21;
  public static final int MAS = 19;
  public static final int CATCH = 18;
}

